### ISSUE TITLE
New icons from requests have low contrast

### ISSUE THREAD

**Issue by pedrofleck** [Vyshnav2255/Notion-Icons-2.0#7]
The newer icons that were requested have lower contrast than the former, the game controller icon is barely visible. Here you can see on my sidebar the language, game controller and burger icons with the others.
![Captura de tela de 2020-05-16 16-55-07](https://user-images.githubusercontent.com/761321/82129005-19aedc00-9796-11ea-9afa-f05c4377b7d7.png)

**Comment by Vyshnav2255** [comment]
Thank you for reporting this.

**Comment by Vyshnav2255** [comment]
Fixed
